name: Publish Python Package

on:
  push:
    branches:
      - fix_lib-ml  # Run this workflow on push events to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest  # Sets the runner to the latest Ubuntu version.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE.

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up a Python environment.
      with:
        python-version: '3.x'  # Specify the Python version.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install setuptools wheel twine  # Install required packages for building and uploading.

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel  # Builds source and wheel package.

    - name: Publish to PyPI
      if: github.event_name == 'push'  # Ensures this step only runs on push events.
      env:
        TWINE_USERNAME: __token__  # Username for PyPI
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # Password or token for PyPI
      run: |
        twine upload dist/*  
